[build]
  # Build command for Vite React app
  command = "npm run build"
  # Publish the dist directory where Vite outputs the built files
  publish = "dist"

[build.environment]
  # Node.js version for building
  NODE_VERSION = "18"

[[redirects]]
  # Handle client-side routing for SPA
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Add security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache fonts
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
